#!/usr/bin/env python
"""Step 3 runner: generate the candidate keyword pool via the reasoning LLM.

Wraps `src.keywords.generator.KeywordGenerator` with the file outputs the
operator reviews: the structured pool (`--output`) and a readable digest
(`--markdown`) that nests each modifier keyword under the broad term it
tightens. Both default under `plans/` (git-ignored — scoping data, not repo
artefacts). Each call makes one live LLM request per batch (default 4
products per batch, 8 products total), so a run takes minutes and spends
real LLM credits.

Usage (from the repo root):

    source .venv/bin/activate && python scripts/generate_keywords.py

The runner exits non-zero when the pool fails validation — nothing is
written for a rejected pool.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from collections import Counter, defaultdict
from pathlib import Path

# Allow `python scripts/generate_keywords.py` (script dir is sys.path[0]).
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.config import settings  # noqa: E402
from src.keywords.generator import (  # noqa: E402
    DEFAULT_BATCH_SIZE,
    CandidateKeyword,
    KeywordGenerationError,
    KeywordGenerator,
)

REPO = Path(__file__).resolve().parents[1]


def write_markdown(path: Path, candidates: list[CandidateKeyword]) -> None:
    """Readable digest: broad/modifier pairs grouped by product."""
    modifiers: defaultdict[str, list[CandidateKeyword]] = defaultdict(list)
    for candidate in candidates:
        if candidate.role == "modifier":
            modifiers[candidate.tightens].append(candidate)
    broad_terms = {c.keyword for c in candidates if c.role == "broad"}

    per_role = Counter(c.role for c in candidates)
    per_pillar = Counter(c.pillar for c in candidates)
    lines = [
        "# Step 3 — candidate supplier keywords (Step 4 input)",
        "",
        f"{len(candidates)} candidate keywords generated by the repo's "
        f"configured reasoning LLM (`{settings.LLM_MODEL}`) via "
        "`scripts/generate_keywords.py`. **Not tracked.**",
        "",
        f"Role split: {dict(per_role)} · Pillars: {dict(per_pillar)}",
        "",
    ]
    for product in dict.fromkeys(c.product for c in candidates):
        lines += [f"## {product}", ""]
        for broad in (c for c in candidates if c.product == product and c.role == "broad"):
            lines.append(f"- **`{broad.keyword}`** — {broad.rationale}")
            for modifier in modifiers.get(broad.keyword, []):
                lines.append(f"  - `{modifier.keyword}` — {modifier.rationale}")
        orphans = [
            c
            for c in candidates
            if c.product == product
            and c.role == "modifier"
            and c.tightens not in broad_terms
        ]
        for orphan in orphans:
            lines.append(
                f"- `{orphan.keyword}` (tightens {orphan.tightens!r}) — "
                f"{orphan.rationale}"
            )
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Step 3: generate and validate the 50-70 candidate keyword pool.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help=f"products per LLM call (default {DEFAULT_BATCH_SIZE})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=REPO / "plans" / "step-3-keywords.json",
        help="structured pool destination",
    )
    parser.add_argument(
        "--markdown",
        type=Path,
        default=REPO / "plans" / "step-3-keywords.md",
        help="readable digest destination",
    )
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    try:
        generator = KeywordGenerator(batch_size=args.batch_size)
        candidates = generator.generate()
    except KeywordGenerationError as exc:
        parser.exit(1, f"error: {exc}\n")

    payload = {
        "keywords": [c.model_dump() for c in candidates],
        "generated_by": settings.LLM_MODEL,
        "note": "candidate pool for the Step 4 Jev gate; not tracked",
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    write_markdown(args.markdown, candidates)

    per_product = Counter(c.product for c in candidates)
    print(f"pool: {len(candidates)} keywords")
    for product, count in per_product.items():
        print(f"  {count:3}  {product}")
    print(f"wrote {args.output} and {args.markdown}")


if __name__ == "__main__":
    main()