#!/usr/bin/env python
"""Step 4 runner: turn the Step-3 gold-standard products into the widened
supplier-search-keyword bank — the GOLD-STANDARD keyword bank.

Wraps `src.keywords.generator.KeywordGenerator` with the file outputs the
operator reviews: the structured bank (`--output`) and a readable digest
(`--markdown`) that nests each modifier keyword under the broad term it
tightens. Both default under `outputs/` (git-ignored — production
deliverables, not repo artefacts). The reasoning LLM is fed the product table
rendered from the Step-3 deliverable in chunks of pool products (each chunk
generates one validated 50–70 pool under the single-pool rules; the merged
bank must clear the bank band around the chunks' summed target), and inside
a chunk the table is batched (default 4 products per call), so a run takes
about an hour at the default 150-product table and spends real LLM credits.

Usage (from the repo root):

    source .venv/bin/activate && python scripts/generate_gold_keywords.py

The runner exits non-zero when a pool or the merged bank fails validation —
nothing is written for a rejected run.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from collections import Counter, defaultdict
from pathlib import Path

# Allow `python scripts/generate_gold_keywords.py` (script dir is sys.path[0]).
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.config import digest_path, settings  # noqa: E402
from src.keywords.generator import (  # noqa: E402
    BANK_MAX_SLACK,
    BANK_MIN_SLACK,
    DEFAULT_BATCH_SIZE,
    DEFAULT_CHUNK_SIZE,
    CandidateKeyword,
    KeywordGenerationError,
    KeywordGenerator,
    chunk_sizes,
    per_product_target,
)

REPO = Path(__file__).resolve().parents[1]


def write_markdown(path: Path, candidates: list[CandidateKeyword]) -> None:
    """Readable digest: broad/modifier pairs grouped by product."""
    modifiers: defaultdict[str, list[CandidateKeyword]] = defaultdict(list)
    for candidate in candidates:
        if candidate.role == "modifier":
            modifiers[candidate.tightens].append(candidate)
    broad_terms = {c.keyword for c in candidates if c.role == "broad"}

    per_role = Counter(c.role for c in candidates)
    per_pillar = Counter(c.pillar for c in candidates)
    lines = [
        "# Step 4 — GOLD-STANDARD supplier keyword bank (Step 5 input)",
        "",
        f"{len(candidates)} keywords generated by the repo's configured "
        f"reasoning LLM (`{settings.LLM_MODEL}`) from the Step-3 "
        "gold-standard products via `scripts/generate_gold_keywords.py`. "
        "**Not tracked.** **This file is the Step-5 keyword bank.**",
        "",
        f"Role split: {dict(per_role)} · Pillars: {dict(per_pillar)}",
        "",
    ]
    for product in dict.fromkeys(c.product for c in candidates):
        lines += [f"## {product}", ""]
        for broad in (c for c in candidates if c.product == product and c.role == "broad"):
            lines.append(f"- **`{broad.keyword}`** — {broad.rationale}")
            for modifier in modifiers.get(broad.keyword, []):
                lines.append(f"  - `{modifier.keyword}` — {modifier.rationale}")
        orphans = [
            c
            for c in candidates
            if c.product == product
            and c.role == "modifier"
            and c.tightens not in broad_terms
        ]
        for orphan in orphans:
            lines.append(
                f"- `{orphan.keyword}` (tightens {orphan.tightens!r}) — "
                f"{orphan.rationale}"
            )
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Step 4: generate and validate the gold-standard keyword bank "
            "from the Step-3 gold-standard products (pool chunks merged "
            "under the bank band)."
        ),
    )
    parser.add_argument(
        "--gold-products",
        type=Path,
        default=Path(settings.GOLD_PRODUCTS_PATH),
        help="Step-3 deliverable to derive the bank from",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help=f"products per LLM call (default {DEFAULT_BATCH_SIZE})",
    )
    parser.add_argument(
        "--max-products",
        type=int,
        default=None,
        help=(
            "overall demand-ranked prefix cap on the eligible gold products "
            "fed to the LLM (default: the generator's own cap; the Step-3 "
            "deliverable stays the full record)"
        ),
    )
    parser.add_argument(
        "--chunk-size",
        type=int,
        default=DEFAULT_CHUNK_SIZE,
        help=f"products per validated pool chunk (default {DEFAULT_CHUNK_SIZE})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(settings.KEYWORD_BANK_PATH),
        help="structured bank destination",
    )
    parser.add_argument(
        "--markdown",
        type=Path,
        default=None,
        help="readable digest destination (default: outputs/md/ beside --output)",
    )
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    markdown_path = args.markdown or digest_path(args.output)
    kwargs = {"batch_size": args.batch_size, "gold_products_path": args.gold_products}
    if args.max_products is not None:
        kwargs["max_products"] = args.max_products
    try:
        generator = KeywordGenerator(**kwargs)
        sizes = chunk_sizes(len(generator.products), args.chunk_size)
        summed_target = sum(
            per_product_target(size) * size for size in sizes
        )
        calls = sum(
            (size + args.batch_size - 1) // args.batch_size for size in sizes
        )
        print(
            f"gold products: {len(generator.products)} of the Step-3 "
            f"deliverable"
        )
        print(
            f"bank plan: {len(sizes)} pool chunk(s), sizes {sizes}; "
            f"target {per_product_target(sizes[0])} keywords per product "
            f"(summed target {summed_target}, band "
            f"{summed_target - BANK_MIN_SLACK}-{summed_target + BANK_MAX_SLACK}); "
            f"~{calls} LLM calls at {args.batch_size} products per call"
        )
        candidates = generator.generate_bank(chunk_size=args.chunk_size)
    except KeywordGenerationError as exc:
        parser.exit(1, f"error: {exc}\n")

    payload = {
        "keywords": [c.model_dump() for c in candidates],
        "generated_by": settings.LLM_MODEL,
        "source_products": len(generator.products),
        "chunks": sizes,
        "note": "GOLD-STANDARD keyword bank for Step 5 dual-supplier "
                "ingestion; not tracked",
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    write_markdown(markdown_path, candidates)

    per_product = Counter(c.product for c in candidates)
    print(f"bank: {len(candidates)} keywords across {len(per_product)} products")
    for product, count in per_product.items():
        print(f"  {count:3}  {product}")
    print(f"wrote {args.output} and {markdown_path}")


if __name__ == "__main__":
    main()
